#!/usr/bin/env python3
"""Download ETP (Equational Theories Project) data for local analysis.

Downloads:
- equations.txt: The 4694 equational laws

Also regenerates synthetic data files in research/data/original/:
- equations.json, implications.json, train_problems.json
These are generated by src/generate_synthetic_data.py (also available via `make generate-data`).

Source: https://github.com/teorth/equational_theories
"""

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
PROJECT_ROOT = Path(__file__).parent.parent

URLS = {
    "equations.txt": (
        "https://raw.githubusercontent.com/teorth/equational_theories/main/data/equations.txt"
    ),
}


def download_file(url: str, dest: Path) -> bool:
    """Download a file from url to dest. Returns True on success."""
    print(f"Downloading {dest.name} from {url}...")
    try:
        urllib.request.urlretrieve(url, dest)
        size = dest.stat().st_size
        print(f"  -> {size:,} bytes saved to {dest}")
        return True
    except (urllib.error.URLError, OSError) as e:
        print(f"  -> FAILED: {e}")
        return False


def parse_equations_file(path: Path) -> list[dict]:
    """Parse the ETP equations.txt format into structured data."""
    equations = []
    with open(path) as f:
        for i, line in enumerate(f, start=1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            equations.append(
                {
                    "id": i,
                    "raw": line,
                }
            )
    return equations


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    success = True
    for name, url in URLS.items():
        dest = DATA_DIR / name
        if dest.exists():
            print(f"Skipping {name} (already exists, {dest.stat().st_size:,} bytes)")
            continue
        if not download_file(url, dest):
            success = False

    # Parse and create a summary
    eq_file = DATA_DIR / "equations.txt"
    if eq_file.exists():
        equations = parse_equations_file(eq_file)
        print(f"\nParsed {len(equations)} equations from equations.txt")

        summary = {
            "total_equations": len(equations),
            "first_5": equations[:5],
            "last_5": equations[-5:],
        }
        summary_path = DATA_DIR / "equations_summary.json"
        with open(summary_path, "w") as f:
            json.dump(summary, f, indent=2)
        print(f"Summary saved to {summary_path}")

    # Regenerate synthetic data files in research/data/original/
    original_dir = PROJECT_ROOT / "research" / "data" / "original"
    synthetic_files = ["equations.json", "implications.json", "train_problems.json"]
    missing = [f for f in synthetic_files if not (original_dir / f).exists()]

    if missing:
        print(f"\nRegenerating synthetic data ({', '.join(missing)})...")
        generate_script = PROJECT_ROOT / "src" / "generate_synthetic_data.py"
        if generate_script.exists():
            result = subprocess.run(
                [sys.executable, str(generate_script)],
                cwd=str(PROJECT_ROOT),
                env={
                    **os.environ,
                    "PYTHONPATH": f"{PROJECT_ROOT / 'src'}:{PROJECT_ROOT / 'tla' / 'python'}",
                },
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                print(
                    f"  -> Failed to regenerate synthetic data:\n{result.stderr}",
                    file=sys.stderr,
                )
                success = False
        else:
            print(f"  -> {generate_script} not found", file=sys.stderr)
            print("  -> Run `make generate-data` manually to create synthetic data")
            success = False
    else:
        print(f"\nSkipping synthetic data (already exists in {original_dir})")

    if success:
        print("\nAll downloads complete.")
    else:
        print("\nSome downloads failed.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
