#!/usr/bin/env python3
"""Generate Lean 4 proof templates from decision procedure results.

This scaffolding supports issue #15: Automate Lean proof generation.
It generates Lean source files containing proof obligations for
equation implications that the decision procedure classifies with
high confidence.

Usage:
    python scripts/generate_lean_proofs.py [--output DIR] [--sample N] [--phase PHASE]

Approach:
    1. Run decision procedure on equation pairs
    2. For TRUE predictions with structural evidence, generate Lean proof stubs
    3. For FALSE predictions with counterexamples, generate Lean counterexample witnesses
    4. Output .lean files that can be checked with `lake build`

Future work (issue #15):
    - Integrate with automated Lean tactic search
    - Feed counterexample magmas as Lean DecidableEq witnesses
    - Connect to the Equational Theories Project's existing proof database
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from etp_equations import ETPEquations  # noqa: E402
from implication_oracle import ImplicationOracle  # noqa: E402
from decision_procedure import DecisionProcedure  # noqa: E402


def generate_true_proof_template(h_id: int, t_id: int, phase: str, reason: str) -> str:
    """Generate a Lean 4 proof template for a TRUE implication."""
    return f"""/-- E{h_id} implies E{t_id}.
    Decision procedure phase: {phase}
    Reason: {reason} -/
theorem e{h_id}_implies_e{t_id} :
    ∀ (M : Type) [Magma M], Equation{h_id} M → Equation{t_id} M := by
  sorry -- TODO: automated proof generation
"""


def generate_false_witness_template(h_id: int, t_id: int, phase: str, reason: str) -> str:
    """Generate a Lean 4 counterexample witness for a FALSE implication."""
    return f"""/-- E{h_id} does NOT imply E{t_id}.
    Decision procedure phase: {phase}
    Reason: {reason} -/
theorem e{h_id}_not_implies_e{t_id} :
    ¬(∀ (M : Type) [Magma M], Equation{h_id} M → Equation{t_id} M) := by
  sorry -- TODO: construct counterexample magma witness
"""


def generate_proofs(
    equations_path: str,
    oracle_path: str,
    output_dir: str,
    sample_size: int = 100,
    phase_filter: str | None = None,
) -> dict:
    """Generate Lean proof files from decision procedure results.

    Returns statistics about generated proofs.
    """
    eqs = ETPEquations(equations_path)
    oracle = ImplicationOracle(oracle_path)
    proc = DecisionProcedure(eqs, oracle)

    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    true_proofs = []
    false_proofs = []
    count = 0

    # Sample equation pairs
    eq_ids = eqs.ids()
    for h_id in eq_ids[:50]:  # First 50 hypotheses
        for t_id in eq_ids[:50]:  # First 50 targets
            if h_id == t_id:
                continue
            if count >= sample_size:
                break

            result = proc.predict(h_id, t_id)
            if phase_filter and phase_filter not in result.phase:
                continue

            if result.prediction:
                true_proofs.append(
                    generate_true_proof_template(h_id, t_id, result.phase, result.reason)
                )
            else:
                false_proofs.append(
                    generate_false_witness_template(h_id, t_id, result.phase, result.reason)
                )
            count += 1

        if count >= sample_size:
            break

    # Write output files
    header = """import EquationalTheories.Basic
import EquationalTheories.Core

/-!
# Auto-generated proof obligations

Generated by scripts/generate_lean_proofs.py from decision procedure results.
These are proof stubs that need to be filled in (replace `sorry` with proofs).
-/

namespace EquationalTheories.Generated

"""

    footer = "\n\nend EquationalTheories.Generated\n"

    if true_proofs:
        true_file = output / "TrueImplications.lean"
        true_file.write_text(header + "\n\n".join(true_proofs) + footer)

    if false_proofs:
        false_file = output / "FalseImplications.lean"
        false_file.write_text(header + "\n\n".join(false_proofs) + footer)

    return {
        "true_proofs": len(true_proofs),
        "false_proofs": len(false_proofs),
        "total": count,
        "output_dir": str(output),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Lean proof templates")
    parser.add_argument("--equations", default="research/data/etp/equations.txt")
    parser.add_argument("--oracle", default="research/data/etp/implications.csv")
    parser.add_argument("--output", default="lean/EquationalTheories/Generated")
    parser.add_argument("--sample", type=int, default=100, help="Number of proof stubs to generate")
    parser.add_argument("--phase", help="Filter by decision procedure phase (e.g. P5-substitution)")
    args = parser.parse_args()

    print("Generating Lean proof templates...")
    stats = generate_proofs(args.equations, args.oracle, args.output, args.sample, args.phase)

    print(f"Generated {stats['true_proofs']} TRUE proof stubs")
    print(f"Generated {stats['false_proofs']} FALSE witness stubs")
    print(f"Output: {stats['output_dir']}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
